#
# Copyright (c) 2012-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation

name: Code Coverage Report
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false
      - name: Start Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/v1.23.2/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --memory=4000mb
      - name: Install CRDs
        run: |
          minikube kubectl -- apply -f https://raw.githubusercontent.com/redhat-appstudio/service-provider-integration-operator/main/config/crd/bases/appstudio.redhat.com_spiaccesstokens.yaml
          minikube kubectl -- apply -f https://raw.githubusercontent.com/redhat-appstudio/service-provider-integration-operator/main/config/crd/bases/appstudio.redhat.com_spiaccesstokenbindings.yaml
          minikube kubectl -- apply -f https://raw.githubusercontent.com/redhat-appstudio/service-provider-integration-operator/main/config/crd/bases/appstudio.redhat.com_spiaccesstokendataupdates.yaml
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run tests
        run: |
         echo "" > coverage.txt
         export MOCK_API=true && go test  ./... -coverprofile coverage.txt
      - name: Codecov
        uses: codecov/codecov-action@v3
